- name: deploy website
  hosts: "{{hosts}}"
  gather_facts: false
  become: true
  tasks:
    - name: Install git
      dnf:
        name: git
        state: present
    - name: Clone git to a local server
      git:
        repo: https://github.com/darrylkelly88/ansibletest.git
        dest: /var/www/
