- name: open web port
  hosts: web
  gather_facts: false
  become: true
  tasks:
    - name: enable port 80
        firewalld:
          zone: public
          port: 80/tcp
          permanent: true
            state: enabled
