- name: restore from backup
  hosts: web
  gather_facts: false
  become: true
  tasks:
    - name: task failed, performing restore from backup
      debug:
        msg: "Task failed running restore job"
