- name: application deployment
  hosts: web
  gather_facts: false
  become: true
  tasks:
    - name: make sure application is not empty
      assert:
        that:
          - "application != ''"

    - name: printing to terminal application information
      debug:
        msg: "This Ansible Playbook will uninstall {{application}}"

    - name: install application
      dnf:
        name: "{{application}}"
        state: absent
      register: result

    - name: printing to terminal application information
      debug:
        msg: "The application: {{application}} has been uninstalled"
      when: result.changed|bool

    - name: printing to terminal application information
      debug:
        msg: "The application: {{application}} was already uninstalled"
      when: not result.changed|bool
